theme: jekyll-theme-minimal
title: Text Analysis for Absolute Beginners with Python
description: This website contains the learning materials for a 2 part workshop on learning text analysis with Python and Constellate.
show_downloads: false # shows download links for the repository
logo: logo.png # can easily be replaced with an institutional logo by uploading a new file
